z=["p.{}".format(x.replace("-","_")) for x in p.query("-text-")]

p.gimp_drawable_is_text_layer
p.gimp_item_is_text_layer

p.gimp_text_fontname
p.gimp_text_get_extents

p.gimp_text_layer_new
p.gimp_text_layer_resize

p.gimp_text_get_extents_fontname

p.gimp_text_layer_get_antialias
p.gimp_text_layer_get_base_direction
p.gimp_text_layer_get_color
p.gimp_text_layer_get_font
p.gimp_text_layer_get_font_size
p.gimp_text_layer_get_hinting
p.gimp_text_layer_get_hint_style
p.gimp_text_layer_get_indent
p.gimp_text_layer_get_justification
p.gimp_text_layer_get_kerning
p.gimp_text_layer_get_language
p.gimp_text_layer_get_letter_spacing
p.gimp_text_layer_get_line_spacing
p.gimp_text_layer_get_markup
p.gimp_text_layer_get_text

p.gimp_text_layer_set_antialias
p.gimp_text_layer_set_base_direction
p.gimp_text_layer_set_color
p.gimp_text_layer_set_font
p.gimp_text_layer_set_font_size
p.gimp_text_layer_set_hinting
p.gimp_text_layer_set_hint_style
p.gimp_text_layer_set_indent
p.gimp_text_layer_set_justification
p.gimp_text_layer_set_kerning
p.gimp_text_layer_set_language
p.gimp_text_layer_set_letter_spacing
p.gimp_text_layer_set_line_spacing
p.gimp_text_layer_set_text

p.gimp_vectors_new_from_text_layer

p.plug_in_script_fu_text_console
p.script_fu_text_circle
